---
title: 'Proof: Degree 3 or Less Polynomials are Vector Spaces'
author: "Bill Cruise (UNCC Student Id: 800932170)"
date: "Wednesday, March 23, 2016"
output: pdf_document
---

$\mathbb{P}_3 (\mathbb{R}) = \{ p(t) : p(t) = p_0 + p_1t + p_2t^2 + p_3t^3; p_0, p_1, p_2, p_3, t \in \mathbb{R} \}$ with

$P + Q = (p_0 + p_1t + p_2t^2 + p_3t^3) + (q_0 + q_1t + q_2t^2 + q_3t^3)$

$= (p_0 + q_0) + (p_1t + q_1t) + (p_2t^2 + q_2t^2) + (p_3t^3 + q_3t^3)$

$= (p_0 + q_0) + (p_1 + q_1)t + (p_2 + q_2)t^2 + (p_3 + q_3)t^3$, and

$cP = c(p_0 + p_1t + p_2t^2 + p_3t^3) = cp_0 + cp_1t + cp_2t^2 + cp_3t^3$

Closure:
===

1. Let $P, Q \in \mathbb{P}_3 (\mathbb{R})$.

$P + Q = R = (p_0 + q_0) + (p_1 + q_1)t + (p_2 + q_2)t^2 + (p_3 + q_3)t^3$. 

$p_0, q_0, p_1, q_1, t, p_2, q_2, p_3, q_3 \in \mathbb{R} \implies (p_0 + q_0), (p_1 + q_1), (p_2 + q_2), (p_3 + q_3), t^2, t^3 \in \mathbb{R}$, and $R \in \mathbb{P}_3$ or lower, so $R \in \mathbb{P}_3 (\mathbb{R})$ or lower.

2. Let $P \in \mathbb{P}_3 (\mathbb{R}), c \in \mathbb{R}$.

$cP = cp_0 + cp_1t + cp_2t^2 + cp_3t^3$.

$c, t, p_0, p_1, p_2, p_3 \in \mathbb{R} \implies cp_0, cp_1t, cp_2t^2, cp_3t^3 \in \mathbb{R}$, so $cP \in \mathbb{P}_3 (\mathbb{R})$ or lower.

Addition:
===

3. Commutativity - $P + Q = Q + P$ for every $P, Q \in \mathbb{P}_3 (\mathbb{R})$

$P + Q = (p_0 + q_0) + (p_1 + q_1)t + (p_2 + q_2)t^2 + (p_3 + q_3)t^3$

$= (q_0 + p_0) + (q_1 + p_1)t + (q_2 + p_2)t^2 + (q_3 + p_3)t^3$ by commutativity of addition in $(\mathbb{R})$.

$(q_0 + p_0) + (q_1 + p_1)t + (q_2 + p_2)t^2 + (q_3 + p_3)t^3$

$= (q_0 + q_1t + q_2t^2 + q_3t^3) + (p_0 + p_1t + p_2t^2 + p_3t^3) = Q + P$.

4. Associativity - $(P + Q) + R = P + (Q + R)$ for every $P, Q, R \in \mathbb{P}_3 (\mathbb{R})$.

$(P + Q) + R = ((p_0 + q_0) + (p_1 + q_1)t + (p_2 + q_2)t^2 + (p_3 + q_3)t^3) + (r_0 + r_1t + r_2t^2 + r_3t^3)$

$= (p_0 + q_0 + r_0) + (p_1 + q_1 + r_1)t + (p_2 + q_2 + r_2)t^2 + (p_3 + q_3 + r_3)t^3$

$= p_0 + (q_0 + r_0) + p_1 + (q_1 + r_1)t + p_2 + (q_2 + r_2)t^2 + p_3 + (q_3 + + r_3)t^3$ by associativity of addition in $(\mathbb{R})$.

$p_0 + (q_0 + r_0) + p_1 + (q_1 + r_1)t + p_2 + (q_2 + r_2)t^2 + p_3 + (q_3 + + r_3)t^3$

$= (p_0 + p_1t + p_2t^2 + p_3t^3) + ((q_0 + r_0) + (q_1 + r_1)t + (q_2 + r_2)t^2 + (q_3 + r_3)t^3) = P + (Q + R)$

5. Exisistence of an additive identity ($\vec{0}$), i.e., there must exist a $\vec{0}$ such that $P + \vec{0} = \vec{0} + P = P$ for every $P \in \mathbb{P}_3 (\mathbb{R})$.

$P + c_0 + c_1t + c_2t^2 + c_3t^3 = (p_0 + c_0) + (p_1 + c_1)t + (p_2 + c_2)t^2 + (p_3 + c_3)t^3$

$= p_0 + p_1t + p_2t^2 + p_3t^3 \implies c_0 = c_1 = c_2 = c_3 = 0$, i.e., $\vec{0} = 0 + 0t + 0t^2 + 0t^3$ is the additive identity of $\mathbb{P}_3 (\mathbb{R})$.

6. Existence of additive inverses, i.e., for every $P \in \mathbb{P}_3 (\mathbb{R})$ there must exist some $Q$ such that $P + Q = Q + P = \vec{0}$.

$P + Q = (p_0 + q_0) + (p_1 + q_1)t + (p_2 + q_2)t^2 + (p_3 + q_3)t^3$

$= 0 + 0t + 0t^2 + 0t^3 \implies q_0 = -p_0, q_1 = -p_1, q_2 = -p_2, and q_3 = -p_3$, so $Q = -p_0 - p_1t - p_2t^2 - p_3t^3$.

Multiplication:
===

7. Distribution of a scalar onto the sum of two vectors, i.e., for every $c \in \mathbb{R}$ and every $P, Q \in \mathbb{P}_3 (\mathbb{R})$, $c(P + Q) = cP + cQ$.

$c(P + Q) = c((p_0 + p_1t + p_2t^2 + p_3t^3) + (q_0 + q_1t + q_2t^2 + q_3t^3))$

$= c(p_0 + p_1t + p_2t^2 + p_3t^3) + c(q_0 + q_1t + q_2t^2 + q_3t^3) = cP + cQ$

8. Distribution of a vector onto the sum of two scalars, i.e., for every $c, d \in \mathbb{R}$ and every $P \in \mathbb{P}_3 (\mathbb{R})$, $(c + d)P = cP + dP$.

$(c + d)P = (c + d)(p_0 + p_1t + p_2t^2 + p_3t^3)$

$= c(p_0 + p_1t + p_2t^2 + p_3t^3) + d(p_0 + p_1t + p_2t^2 + p_3t^3) = cP + dP$

9. Scalar multiplication of a scalar multiplication, i.e., for every $c, d \in \mathbb{R}$ and $P \in \mathbb{P}_3 (\mathbb{R})$, $c(dP) = (cd)P$.

$c(dP) = c(d(p_0 + p_1t + p_2t^2 + p_3t^3))$

$= cd(p_0 + p_1t + p_2t^2 + p_3t^3) = (cd)P$

10. Scalar multiplication with the multiplicative identity of the field ($\mathbb{R}$), i.e., for every $P \in \mathbb{P}_3 (\mathbb{R}), 1P = P$.

$1P = 1(p_0 + p_1t + p_2t^2 + p_3t^3) = 1p_0 + 1p_1t + 1p_2t^2 + 1p_3t^3$

$= p_0 + p_1t + p_2t^2 + p_3t^3 = P$

